version: '3.8'
services:
  app:
    image: webdevops/php-nginx:8.2
    depends_on:
      - db
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8000:80"
    volumes:
      - ./:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  db_test:
      image: mysql:8.0
      container_name: laravel_db_test
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ${DB_TEST_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_TEST_PASSWORD}
      ports:
        - "3307:3306"
      volumes:
        - dbdata_test:/var/lib/mysql

volumes:
  dbdata:
  dbdata_test:
